### PR TITLE
call callback only when its not null

### PR DESCRIPTION
**Pull request by oshanrube**
this is due to an error occurred when trying to run test.py

### CODE REVIEW

**Comment by micahg** [comment]
Hi,

Thanks for the PR. Can you provide some steps to reproduce? Under what circumstances was the callback null?

**Comment by micahg** [comment]
OK, I reproduced. IMO, lets just fix test.py to pass in progress as the third parameter on line 35. If you want I can make the change or we can update the PR

**Comment by oshanrube** [comment]
OK in that case we should remove the default value None as well

**Comment by micahg** [comment]
makes sense to me.

**Comment by micahg** [comment]
merged into the official matrix branch. thanks for the help.

**Pull request merged**
