### PR TITLE
Update code to python3 for Kodi-v19 usage

### PR DESCRIPTION
**Pull request by smf007**
The code has been updated to python3 for usage with Kodi-v19.

### CODE REVIEW

**Comment by smf007** [comment]
Thanks.  I'll look into what change is required for:

> ERROR : Window Translator: Can't find window infodialog

I hadn't tested this any further then live streams, so not really surprised.

**Comment by smf007** [comment]
Fixed that error now.  Also noticed the icon and fanart were not getting picked up, fixed those while I was at it.

**Comment by newf276** [comment]
Wow, fast work.  Yes I forgot to mention the icon and fanart, but fixed that myself.  Actually added a black and white version.  Will give the new version a try and report back.  Much appreciated brother.

**Comment by newf276** [comment]
Works perfectly now, thank you very much.  Any chance you would know how to fix this heart plugin: https://github.com/divingmule/plugin.audio.iheart

Willing to donate for your efforts...

Ian

**Comment by micahg** [comment]
Hey -- I'll have a look and merge -- sorry about the delay

**Comment by micahg** [comment]
OK, this was merged into the matrix repo library.

**Pull request merged**
